### ISSUE TITLE
candle list showing constant value in specific position?

### ISSUE THREAD

**Issue by blinksmith** [binary-com/binary-bot#294]
![bug1](https://user-images.githubusercontent.com/409976/27892321-2f2ea344-6229-11e7-8dc0-1cc054e4a184.PNG)

**Comment by aminmarashi** [comment]
Thanks for reporting @blinksmith , this is the same as #286 . We'll fix soon.

**Comment by aminmarashi** [comment]
This should be fixed, could you please check again?

**Comment by blinksmith** [comment]
I tried on latest master branch and dev branch, also tried on old version of bot (downloaded on June 22) 
but the result is still the same
![capture](https://user-images.githubusercontent.com/409976/27963113-30348a98-635e-11e7-805b-75939d519f48.PNG)

**Comment by blinksmith** [comment]
candleListBug.xml
```xml
<xml xmlns="http://www.w3.org/1999/xhtml" collection="false">
  <block type="trade" id="*MR5LN{uwx01fw84Efjp" x="4" y="6">
    <field name="MARKET_LIST">volidx</field>
    <field name="SUBMARKET_LIST">random_index</field>
    <field name="SYMBOL_LIST">R_100</field>
    <field name="TRADETYPECAT_LIST">callput</field>
    <field name="TRADETYPE_LIST">risefall</field>
    <field name="TYPE_LIST">both</field>
    <field name="CANDLEINTERVAL_LIST">60</field>
    <statement name="SUBMARKET">
      <block type="tradeOptions" id="%-7_dOFUjpfkwJ}[ChAO">
        <field name="DURATIONTYPE_LIST">t</field>
        <field name="CURRENCY_LIST">USD</field>
        <value name="DURATION">
          <shadow type="math_number" id="d0(doV5U3LQ;Hi}J[@Az">
            <field name="NUM">5</field>
          </shadow>
        </value>
        <value name="AMOUNT">
          <shadow type="math_number" id=":}Ak|3ocGs~@e{;,,Y|T">
            <field name="NUM">1</field>
          </shadow>
        </value>
      </block>
    </statement>
  </block>
  <block type="before_purchase" id="i-CIx.(Onm4?ihxzA}Y]" x="0" y="251">
    <statement name="BEFOREPURCHASE_STACK">
      <block type="notify" id="|D%J)E:34?iTJ9FFWTB=" disabled="true">
        <field name="NOTIFICATION_TYPE">info</field>
        <value name="MESSAGE">
          <shadow type="text" id="U@#JA]0tRkYPzN6v%i#6">
            <field name="TEXT">abc</field>
          </shadow>
          <block type="logic_compare" id="v)ohx^CWv`Jl=D/}zm$D">
            <field name="OP">EQ</field>
            <value name="A">
              <block type="lists_getIndex" id="[EZk$4Y0lpfU10N9=(Qv">
                <mutation statement="false" at="true"></mutation>
                <field name="MODE">GET</field>
                <field name="WHERE">FROM_END</field>
                <value name="VALUE">
                  <block type="ohlc_values" id="b-fD0(eZH8Vz}E]0~Q6w">
                    <field name="OHLCFIELD_LIST">close</field>
                  </block>
                </value>
                <value name="AT">
                  <block type="math_number" id=";BLQ2MwDDQdHVA#xkb_;">
                    <field name="NUM">1</field>
                  </block>
                </value>
              </block>
            </value>
            <value name="B">
              <block type="lists_getIndex" id="F,Dc5Cqv,PB%#A*7tAY4">
                <mutation statement="false" at="false"></mutation>
                <field name="MODE">GET</field>
                <field name="WHERE">LAST</field>
                <value name="VALUE">
                  <block type="ohlc_values" id="~8$#u#[5-:A+pfpH^Noc">
                    <field name="OHLCFIELD_LIST">close</field>
                  </block>
                </value>
              </block>
            </value>
          </block>
        </value>
        <next>
          <block type="notify" id="HmkQ%G~e$)Qu4ls0NOs7" disabled="true">
            <field name="NOTIFICATION_TYPE">error</field>
            <value name="MESSAGE">
              <shadow type="text" id="U@#JA]0tRkYPzN6v%i#6">
                <field name="TEXT">abc</field>
              </shadow>
              <block type="lists_getIndex" id="Q_yZp?MX23C.5qR:t^rU">
                <mutation statement="false" at="true"></mutation>
                <field name="MODE">GET</field>
                <field name="WHERE">FROM_END</field>
                <value name="VALUE">
                  <block type="ohlc_values" id="+yOpb7sHaOAdx}VN@toa">
                    <field name="OHLCFIELD_LIST">close</field>
                  </block>
                </value>
                <value name="AT">
                  <block type="math_number" id="($S?$V:rMVLxutxLS_Rs">
                    <field name="NUM">2</field>
                  </block>
                </value>
              </block>
            </value>
            <next>
              <block type="notify" id="EYH[:M{oLKriTA6uMEj)" disabled="true">
                <field name="NOTIFICATION_TYPE">warn</field>
                <value name="MESSAGE">
                  <shadow type="text" id="U@#JA]0tRkYPzN6v%i#6">
                    <field name="TEXT">abc</field>
                  </shadow>
                  <block type="lists_getIndex" id="9@j@+Oaaxt7bOOv[l%W{">
                    <mutation statement="false" at="true"></mutation>
                    <field name="MODE">GET</field>
                    <field name="WHERE">FROM_END</field>
                    <value name="VALUE">
                      <block type="ohlc_values" id="1)SFq|WW;ZlO(o#-;2vL">
                        <field name="OHLCFIELD_LIST">close</field>
                      </block>
                    </value>
                    <value name="AT">
                      <block type="math_number" id=";|pi,wTBdq.rd-0W045=">
                        <field name="NUM">3</field>
                      </block>
                    </value>
                  </block>
                </value>
                <next>
                  <block type="notify" id="Hg.tZ(rtz|0@FB=H+KpC">
                    <field name="NOTIFICATION_TYPE">success</field>
                    <value name="MESSAGE">
                      <shadow type="text" id="U@#JA]0tRkYPzN6v%i#6">
                        <field name="TEXT">abc</field>
                      </shadow>
                      <block type="ohlc" id="SojxNZKx*7My0tsiIh$D"></block>
                    </value>
                  </block>
                </next>
              </block>
            </next>
          </block>
        </next>
      </block>
    </statement>
  </block>
</xml>
```

**Comment by aminmarashi** [comment]
Sorry @blinksmith, my bad. I mistook this inquiry with a bug we had at the time. 
Seems like your blocks are disabled (yellowish blocks are disabled, you can enable them by right clicking on them and click on Enable.
<img width="251" alt="screen shot 2017-07-08 at 6 06 45 am" src="https://user-images.githubusercontent.com/6560964/27978715-b5548e0e-63a3-11e7-8a15-357aebbbf12c.png">

I think your blocks are working as expected let me explain them:
Candles are historical data used by many traders to analyze the market trade, more info on them [here](https://en.wikipedia.org/wiki/Candlestick_chart)
In Binary Bot candles are JavaScript objects, which are only meant to be used for very advanced developers (probably a bad decision in the first place to include the candle blocks which may cause confusion).
Never use the candle blocks that give an object, unless you know what you're doing: (<img width="92" alt="screen shot 2017-07-08 at 6 08 02 am" src="https://user-images.githubusercontent.com/6560964/27978743-dc39efe6-63a3-11e7-952e-0f2c7aeacbac.png">, <img width="217" alt="screen shot 2017-07-08 at 6 08 12 am" src="https://user-images.githubusercontent.com/6560964/27978747-e0e350d2-63a3-11e7-8d0a-f2c2912f533f.png">)

Instead, use candle blocks that have field selection and give a number:
<img width="271" alt="screen shot 2017-07-08 at 6 09 04 am" src="https://user-images.githubusercontent.com/6560964/27978768-f91f7842-63a3-11e7-93de-650710f3dab7.png">
Of course, there might be some users that need the candle blocks and they will probably find out how to use them (take a look at Tools -> Candle)

If you're using <img width="282" alt="screen shot 2017-07-08 at 6 15 06 am" src="https://user-images.githubusercontent.com/6560964/27978901-db2dafd8-63a4-11e7-8dd1-1d0b2194cdc8.png">, the corresponding candles from the chart will be:

![candlestick](https://user-images.githubusercontent.com/6560964/27978602-13f63a1c-63a3-11e7-82d8-c7e902208531.png)

**Comment by blinksmith** [comment]
it's disabled by me, I intentionally did it to show second result on picture 2.
if notification that showed in picture 2 is come as expected so please focus on picture 1

I have no problem with
"in candles list read Open # from end 1" 

my problem is in
"in candles list read Open # from end 2"
"in candles list read Open # from end 3"
their result is not come as expected, because their result never changed.

i need to use candle instead of sticklist because i building indicator that based on candle.

**Comment by blinksmith** [comment]
now i got the answer 
value in "candles list # from end 1" is always changes every tick
while value in "candles list # from end 2" and "candles list # from end 3" and so on is changed after 1 minute.

**Comment by Mightton** [comment]
blinksmith What kind of bot are you trying to make ? I'm trying to figure out candle stick patterns. What do you think about that ? And how is your knowledge of if ? I have tried many different ways but seems to get stuck at the same point everytime...
