### ISSUE TITLE
Sell profit/loss block returning error 

### ISSUE THREAD

**Issue by garshom** [binary-com/binary-bot#2997]
Hello Team,

I need your help 

Deriv.app/bot Sell profit/loss block is returning error `this.data.get is not a function ` instead of returning possible profit or loss value 

Block configuration

<img width="732" alt="Screenshot 2020-09-07 at 21 33 32" src="https://user-images.githubusercontent.com/6675709/92412193-a91c3880-f153-11ea-8d2e-2cbcacbfe145.png">

Error Returned when block excutes

<img width="372" alt="Screenshot 2020-09-07 at 21 22 20" src="https://user-images.githubusercontent.com/6675709/92412199-ad485600-f153-11ea-8ac4-bda337478e16.png">

**Comment by aaron-binary** [comment]
Hey @garshom,

Let us look into this, this doesn't look right.

Regards,
Aaron

**Comment by garshom** [comment]
Hey @aaron-binary 

Issue not resolved yet , did you try to get a workaround 

Regards
Garshom

**Comment by aaron-binary** [comment]
Hey @garshom,

We've found the issue and will release a fix soon.

Regards,
Aaron

**Comment by aaron-binary** [comment]
This should be fixed now @garshom.

**Comment by garshom** [comment]
Hello buddy, error is still coming.

take a look at this 
<img width="1102" alt="Screenshot 2020-09-18 at 14 40 09" src="https://user-images.githubusercontent.com/6675709/93595272-1d5ea380-f9c0-11ea-8ed3-5dca82368929.png">
